---
ansible_python_interpreter: /usr/bin/python3

pip_install_packages:
  - name: docker

docker_users:
  - ubuntu

redmine_image: "redmine:6.0"
redmine_port: 3000
redmine_app_dir: /opt/redmine

db_host: "{{ lookup('env', 'DB_HOST') | mandatory }}"
db_port: "{{ lookup('env', 'DB_PORT') | mandatory }}"
db_name: "{{ lookup('env', 'DB_NAME') | mandatory }}"
db_user: "{{ lookup('env', 'DB_USER') | mandatory }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') | mandatory }}"
redmine_secret_key: "{{ lookup('env', 'REDMINE_SECRET_KEY_BASE') | mandatory }}"
